services:
  - type: web
    name: cuppa
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run dev:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
